### ISSUE TITLE
m.me stuck link

### ISSUE THREAD

**Issue by jidanni** [OsmHackTW/osmtw-ghpage#280]
https://m.me/openstreetmaptaiwan 停住。 
I used the  Brave browser on a cell phone and just got a empty black page.

**Comment by assanges** [comment]
Out of Scope. 
My apologies, but this was due to your browser environment, not a repo-related issue.
Please check your browser settings.

See Also:
* [Messenger.com not working - Brave Community](https://community.brave.com/t/messenger-com-not-working/283346)
