### ISSUE TITLE
Looks like clickable links

### ISSUE THREAD

**Issue by jidanni** [OsmHackTW/osmtw-ghpage#281]
![Screenshot_20221228-123904_Chrome Dev.jpg](https://user-images.githubusercontent.com/1230959/209758344-6e2e659b-c1e5-41ba-a39d-14e4d77c085f.jpg)

圖中

> 了解更多 FIND OUT MORE

> 台灣社群據點 COMMUNITY HUBS

長得像可按的連結。

**Comment by assanges** [comment]
Style revamped as follows:

![image](https://user-images.githubusercontent.com/4113063/221400973-115ec650-9399-4ec8-b11b-14321eec9710.png)
